### PR TITLE
Merge operator

### LINKED ISSUE #133: Merge operator
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Use-cases

Merging tuples and functions is desirable. Merging two tuples combines all rhs attributes and any lhs attributes whose name isn't on the rhs into a new tuple. For example, merging `(a: 1, b: 2)` and `(b: 3, c: 4)` produces `(a: 1, b: 3, c: 4)`.

This is already implemented as `+`, but this operator should be strictly reserved for its common numeric interpretation. In future, libraries should be able to implement arithmetic over tuples, e.g.: `(x: 1, y: 2) + (x: 3, y: -1) = (x: 4, y: 1)`, which would conflict with the current `+` semantic.

### Proposed Solution

The proposed syntax is `a +> b`. The syntactic asymmetry emphasises the semantic asymmetry (b's attributes take priority over a's).

### Alternatives Considered

`a +> b` is slightly confusing since the directionality might give the impression that a's attributes override b's.

| syntax | notes |
|:-|:-|
| `a <+ b` | Infeasible, since it currently parses as `a < +b`. |
| `a +< b` | Confusing. Doesn't look like a single operator. |
| `a + b` | As discussed above, this should be reserved for the common arithmetic meaning. |
| `a ++ b` | Applies to special sets (arrays, strings, ...) and has a different semantic (applies an offset to every `@` on the RHS). |
| `a merge b` | Adds a keyword and is a bit verbose for what is likely to be a very common operation, especially considering #485. |

### Possible extension to dictionaries

Dictionaries have similar behaviour to tuples. `+>` could also be made to work for them. This technically violates the principle of syntactic transparency (what you get can be inferred directly from what you see). But tuples and dicts are close enough cousins that it's probably OK to make an exception for them.

### PR DESCRIPTION
**Pull request by ericzhang6222**
Fixes #133  .

Changes proposed in this pull request:
- Support Dict
- 

Checklist:
- [x] Added related tests
- [x] Made corresponding changes to the documentation

### CODE REVIEW

File: rel/expr_binary.go [hunk 1]
```diff
@@ -306,7 +307,28 @@ func evalValForAddArrow(lhs, rhs Value) (Value, error) {
...
 
+	if lhs, ok := lhs.(Dict); ok {
+		if rhs, ok := rhs.(Dict); ok {
+			return mergeDicts(lhs, rhs), nil
+		}
+	}
+
 	return nil, errors.Errorf(
-		"Both args to %q must be tuples, not %T and %T",
+		"Both args to %q must be tuples or dicts, not %T and %T",
```
Comment (orlade-anz) [inline rel/expr_binary.go:317]: Nit: presumably you can't merge a dict into a tuple
```suggestion
		"Both args to %q must be both tuples or both dicts, not %T and %T",
```

File: syntax/expr_binary_test.go [hunk 2]
```diff
@@ -19,13 +19,19 @@ func TestRelationCall(t *testing.T) {
 
 func TestOpsAddArrow(t *testing.T) {
 	t.Parallel()
+	// Tuples
```
Comment (orlade-anz) [inline syntax/expr_binary_test.go:22]: Please create separate test `func`s for different test cases instead of mixing them in one.

File: syntax/expr_binary_test.go [hunk 3]
```diff
@@ -19,13 +19,19 @@ func TestRelationCall(t *testing.T) {
...
-	AssertCodesEvalToSameValue(t, `(a: 1, b: 2) +> (b: 3, c: 4)`, `(a: 1, b: 3, c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (b: 3, c: 4)`, `(a: 1, b: 3, c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (b: (c: 4), c: 4)`, `(a: 1, b: (c: 4), c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (a: (b: 1), b: (c: 4))`, `(a: (b: 1), b: (c: 4))`)
+	// Dicts
+	AssertCodesEvalToSameValue(t, `{'a': 1, 'b': 3, 'd': 4}`, `{'a': 1, 'b': 2} +> {'b': 3, 'd': 4}`)
+	AssertCodesEvalToSameValue(t, `{'a': 1, 'b': 3, 'd': 4}`, `{'a': 1, 'b': {'a': 2}} +> {'b': 3, 'd': 4}`)
+	AssertCodesEvalToSameValue(t, `{'a': {'c': 2}}`, `{'a': {'b': 1}} +> {'a': {'c': 2}}`)
 
+	//
```
Comment (orlade-anz) [inline syntax/expr_binary_test.go:34]: These can be a separate case as well

Comment (orlade-anz) [reply syntax/expr_binary_test.go:34]: Also, maybe add a test for lists and strings? They're more dict-like than sets and ints

File: rel/expr_binary.go [hunk 4]
```diff
@@ -306,7 +307,28 @@ func evalValForAddArrow(lhs, rhs Value) (Value, error) {
...
+func mergeDicts(lhs Dict, rhs Dict) Dict {
+	tempMap := lhs.m
+
+	for e := rhs.DictEnumerator(); e.MoveNext(); {
+		key, value := e.Current()
+
+		if lhs.m.Has(key) {
+			tempMap = tempMap.Without(frozen.NewSet(key))
+		}
+		tempMap = tempMap.With(key, value)
```
Comment (nofun97) [inline rel/expr_binary.go:330]: I don't think you need to do a `Without` and then a `With` operation. Just `With` should do it, does it not work?

File: syntax/expr_binary_test.go [hunk 5]
```diff
@@ -17,15 +17,27 @@ func TestRelationCall(t *testing.T) {
...
+	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 4), c: 4)`, `(a: 1, b: (c: 2)) +> (b: (c: 4), c: 4)`)
+	AssertCodesEvalToSameValue(t, `(a: (b: 1), b: (c: 4))`, `(a: 1, b: (c: 2)) +> (a: (b: 1), b: (c: 4))`)
+}
 
-	AssertCodesEvalToSameValue(t, `(a: 1, b: 2) +> (c: 3, d: 4)`, `(a: 1, b: 2, c: 3, d: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: 2) +> (b: 3, c: 4)`, `(a: 1, b: 3, c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (b: 3, c: 4)`, `(a: 1, b: 3, c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (b: (c: 4), c: 4)`, `(a: 1, b: (c: 4), c: 4)`)
-	AssertCodesEvalToSameValue(t, `(a: 1, b: (c: 2)) +> (a: (b: 1), b: (c: 4))`, `(a: (b: 1), b: (c: 4))`)
+func TestOpsAddArrowForDicts(t *testing.T) {
```
Comment (nofun97) [inline syntax/expr_binary_test.go:29]: do another test where both `lhs` and `rhs` have no mutual keys. Do the same for tuples.
