### PR TITLE
Includes source context in arr.ai evaluation error

### LINKED ISSUE #136: Includes source context when arr.ai evaluations crash
### Current arrai Version
v0.1.0

### Use-cases
Includes filename, line number, column number in evaluation crash error message.

### References
- #88

### PR DESCRIPTION
**Pull request by ChloePlanet**
Fixes #136  .

Changes proposed in this pull request:
- Add Scanner function to `type Expr interface`
- Embed struct `ExprScanner` which implements `Scanner` function into Exprs and Values.
- Add source context including filename, line number and column number to `Eval` error

before:
image

after:
image

### CODE REVIEW

File: cmd/arrai/eval.go [hunk 1]
```diff
@@ -19,7 +19,7 @@ var evalCommand = &cli.Command{
 }
 
 func evalImpl(source string, w io.Writer) error {
-	return evalExpr(syntax.NoPath, source, w)
+	return evalExpr(".", source, w)
```
Comment (marcelocantos) [inline cmd/arrai/eval.go:22]: Is this change necessary? The original intent was to disallow imports when there is no source file.

Comment (ChloePlanet) [reply cmd/arrai/eval.go:22]: Yes. Actually `"."` is the original code. I thought `syntax.NoPath` would be better so I changed it to NoPath. Then I found out `arrai e "//./examples/simple/simple"` cannot find the right file path with `NoPath`.

Comment (marcelocantos) [reply cmd/arrai/eval.go:22]: Sorry, I meant to retract this yesterday when I realised it makes perfect sense, but forgot. All good.
