### PR TITLE
Fixes #401, allows arrai -d path/to/file.arrai

### LINKED ISSUE #401: arrai -d path/to/file.arrai does not work
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Description
The command `arrai -d path/to/file.arrai` does not work

### Steps to Reproduce
1. Run `arrai -d path/to/file.arrai`

**Expected behavior:**
runs the file and drops into shell if there's failure

**Actual behavior:**
```
Incorrect Usage: flag provided but not defined: -d

NAME:
   arrai run - evaluate an arrai file

USAGE:
   arrai run [command options] [arguments...]

OPTIONS:
   --help, -h  show help (default: false)

INFO[0000] flag provided but not defined: -d
```
* Debug&Crash Output

### Your Environments
```sh
$ go version


```

### PR DESCRIPTION
**Pull request by nofun97**
Fixes #401.

Changes proposed in this pull request:
- Allows the use of global flags in the command `arrai file.arrai` 

For context, I built this feature where user can do the command `arrai file.arrai`. The trick was to transform the command internally to `arrai run file.arrai`. But yesterday's feature, the debug flag, messed that up, this PR will handle any global flags in the future, so user can do `arrai -d --any-other-flag file.arrai` and have it translated to `arrai -d --any-other-flag run file.arrai`

Checklist:
- [x] Added related tests
- [ ] Made corresponding changes to the documentation

### CODE REVIEW

File: cmd/arrai/command_util.go [hunk 1]
```diff
@@ -28,3 +28,30 @@ func fetchCommand(args []string) string {
...
+
+	for _, f := range globalFlags {
+		for _, n := range f.Names() {
+			globalFlagsMap[n] = struct{}{}
+		}
+	}
+
+	for i, a := range args[1:] {
+		if strings.HasPrefix(a, "-") {
+			name := strings.TrimLeftFunc(a, func(r rune) bool { return r == '-' })
```
Comment (orlade-anz) [inline cmd/arrai/command_util.go:44]:
```suggestion
			name := strings.TrimLeft(a, "-")
```

Comment (nofun97) [reply cmd/arrai/command_util.go:44]: I needed to use the `TrimLeftFunc` so that it can trim both `-d` and `--debug`. Just using `TrimLeft` will only handle `-d`.

Comment (nofun97) [reply cmd/arrai/command_util.go:53]: nevermind, I was misled!!
